#!/usr/bin/env python3
"""Build blog posts from Markdown to HTML."""

import re
import sys
import textwrap
from datetime import datetime
from pathlib import Path

try:
    import markdown
    import yaml
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("Missing dependencies. Install with: pip install markdown pyyaml Pillow")
    sys.exit(1)

CONTENT_DIR = Path("content/posts")
OUTPUT_DIR = Path("posts")
FONT_PATH = Path("files/fonts/EBGaramond.ttf")
OG_DIR = OUTPUT_DIR / "og"
INDEX_PATH = Path("index.html")
ORDER_PATH = Path("content/curated-order.txt")

ORDER_HEADER = """\
# Curated order for the "Writing & talks" section of index.html.
#
# Reorder the titles within each [group] to change the site's "Curated" sort.
# Top line = shown first. The "Recent" sort is generated automatically from
# dates, so it lives nowhere here.
#
# `python3 build.py` keeps this file in sync with index.html: new items are
# appended to their group and removed items are dropped. You only ever move
# lines around; leave the [group] headers alone.
"""

TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - David Rein</title>
    <link rel="stylesheet" href="../styles.css">
    <link rel="apple-touch-icon" sizes="180x180" href="../files/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../files/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../files/favicon/favicon-16x16.png">
    <link rel="manifest" href="../files/favicon/site.webmanifest">
    <meta name="description" content="{description}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description}">
    <meta property="og:image" content="https://idavidrein.com/posts/og/{slug}.png">
    <meta property="og:type" content="article">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{title}">
    <meta name="twitter:description" content="{description}">
    <meta name="twitter:image" content="https://idavidrein.com/posts/og/{slug}.png">
</head>
<body>
    <div class="page">
        <nav class="post-nav">
            <a href="/">&larr; Home</a>
        </nav>

        <article class="post">
            <header class="post-header">
                <h1>{title}</h1>
                <time class="post-date" datetime="{date_iso}">{date_display}</time>
            </header>

            <div class="post-body">
                {body}
            </div>
        </article>
    </div>
    <script src="../footnotes.js"></script>
    <script src="../lightbox.js"></script>
</body>
</html>
"""


def parse_frontmatter(text):
    """Parse YAML frontmatter from markdown text."""
    if not text.startswith("---"):
        raise ValueError("No frontmatter found")
    end = text.index("---", 3)
    meta = yaml.safe_load(text[3:end])
    body = text[end + 3 :].strip()
    return meta, body


def process_footnotes(html):
    """Convert bottom-of-page footnotes into inline popup spans."""
    # Find the footnote section generated by python-markdown
    fn_match = re.search(
        r'<div class="footnote">\s*<hr\s*/?>\s*<ol>(.*?)</ol>\s*</div>',
        html,
        re.DOTALL,
    )
    if not fn_match:
        return html

    # Extract each footnote's content
    footnotes = {}
    for li in re.finditer(
        r'<li id="fn:(.+?)">\s*(.*?)\s*</li>', fn_match.group(1), re.DOTALL
    ):
        fn_id = li.group(1)
        content = li.group(2)
        # Remove the backref link and its preceding non-breaking space
        content = re.sub(
            r"\s*&#160;\s*<a [^>]*class=\"footnote-backref\"[^>]*>.*?</a>",
            "",
            content,
        )
        content = content.strip()
        # Unwrap single-paragraph footnotes
        if content.startswith("<p>") and content.endswith("</p>") and content.count("<p>") == 1:
            content = content[3:-4].strip()
        footnotes[fn_id] = content

    # Remove the footnote section
    html = html[: fn_match.start()] + html[fn_match.end() :]

    # Replace each reference with a popup span
    def replace_ref(m):
        fn_id = m.group(1)
        num = m.group(2)
        content = footnotes.get(fn_id, "")
        return (
            f'<span class="footnote-ref" tabindex="0" role="button" '
            f'aria-label="Footnote {num}">'
            f"<sup>{num}</sup>"
            f'<span class="footnote-popup" role="tooltip">{content}</span>'
            f"</span>"
        )

    # fnref\d* handles repeated references (fnref2:, fnref3:, etc.)
    html = re.sub(
        r'<sup id="fnref\d*:(.+?)"><a class="footnote-ref" href="#fn:.+?">(\d+)</a></sup>',
        replace_ref,
        html,
    )

    return html


def _wrap_text(title, font, max_w):
    """Word-wrap title by measuring with the font."""
    words = title.split()
    lines = []
    current = ""
    for word in words:
        test = f"{current} {word}".strip()
        if font.getbbox(test)[2] > max_w and current:
            lines.append(current)
            current = word
        else:
            current = test
    if current:
        lines.append(current)
    return lines


def generate_og_image(title, slug):
    """Generate a 1200x630 OG image with the post title."""
    W, H = 1200, 630
    BG = (247, 245, 242)  # --bg
    INK = (31, 41, 51)  # --ink
    pad_x = 80

    MUTED = (107, 114, 128)  # --muted
    font_site = ImageFont.truetype(str(FONT_PATH), size=56)
    site_h = 100  # space reserved for site name at bottom

    # Pick the largest font size that fits the title above the site name
    max_text_w = W - 2 * pad_x
    for size in range(140, 30, -2):
        font = ImageFont.truetype(str(FONT_PATH), size=size)
        line_h = int(size * 1.35)
        lines = _wrap_text(title, font, max_text_w)
        text_h = line_h * len(lines)
        if text_h <= H - 80 - site_h:
            break

    img = Image.new("RGB", (W, H), BG)
    draw = ImageDraw.Draw(img)

    # Center title vertically in the space above the site name
    title_area_h = H - site_h
    y = (title_area_h - text_h) // 2
    for line in lines:
        draw.text((pad_x, y), line, fill=INK, font=font)
        y += line_h

    # Site name at bottom
    draw.text((pad_x, H - site_h), "idavidrein.com", fill=MUTED, font=font_site)

    out_path = OG_DIR / f"{slug}.png"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_path, "PNG")


def open_links_in_new_tab(html):
    """Add target="_blank" rel="noreferrer" to external links."""
    return re.sub(r"<a ", '<a target="_blank" rel="noreferrer" ', html)


IMG_TAG_RE = re.compile(r'<img\b[^>]*\bsrc="([^"]+)"[^>]*>')


def _image_has_transparency(path):
    """True only if the image file has at least one non-opaque pixel.

    RGBA/palette containers that happen to be fully opaque (min alpha 255)
    return False, so screenshots saved as RGBA don't get a backing they
    don't need."""
    try:
        with Image.open(path) as im:
            if im.mode not in ("RGBA", "LA") and not (
                im.mode == "P" and "transparency" in im.info
            ):
                return False
            return im.convert("RGBA").getchannel("A").getextrema()[0] < 255
    except (FileNotFoundError, OSError):
        return False


def mark_transparent_images(html):
    """Tag <img>s whose local source has real transparency with
    data-transparent="true".

    lightbox.js reads this to give only those images a solid backing when
    they're shown against the dark lightbox backdrop. Doing the alpha check
    here (at build time) instead of via a runtime canvas means it also works
    when the page is opened over file:// — where reading a local image back
    off a canvas throws a security error.
    """

    def repl(m):
        tag = m.group(0)
        src = m.group(1)
        if src.startswith(("http://", "https://", "//", "data:")):
            return tag
        # Post HTML lives in posts/, so "../files/x" resolves from repo root.
        rel = src[3:] if src.startswith("../") else src.lstrip("/")
        if "data-transparent" in tag or not _image_has_transparency(Path(rel)):
            return tag
        return tag.replace("<img", '<img data-transparent="true"', 1)

    return IMG_TAG_RE.sub(repl, html)


def build_post(md_path):
    """Convert a single markdown file to HTML."""
    text = md_path.read_text()
    meta, body_md = parse_frontmatter(text)

    md = markdown.Markdown(extensions=["footnotes", "smarty"])
    body_html = md.convert(body_md)
    body_html = process_footnotes(body_html)
    body_html = open_links_in_new_tab(body_html)
    body_html = mark_transparent_images(body_html)

    date = meta["date"]
    if isinstance(date, str):
        date = datetime.strptime(date, "%Y-%m-%d")
    # PyYAML parses `date: YYYY-MM-DD` as datetime.date; strptime gives datetime.
    # Normalize to a plain date so it sorts alongside external items' dates.
    date = date.date() if isinstance(date, datetime) else date
    date_iso = date.strftime("%Y-%m-%d")
    date_display = f"{date.strftime('%B')} {date.day}, {date.year}"

    slug = meta.get("slug", md_path.stem)
    out_path = OUTPUT_DIR / f"{slug}.html"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        TEMPLATE.format(
            title=_escape_attr(meta["title"]),
            description=_escape_attr(meta.get("description", "")),
            date_iso=date_iso,
            date_display=date_display,
            body=body_html,
            slug=slug,
        )
    )
    generate_og_image(meta["title"], slug)
    print(f"  {md_path} -> {out_path}")
    return slug, date.year, meta.get("description", ""), date


def _escape(text):
    """HTML-escape for element text (& < >); quotes stay literal to match the hand style."""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _escape_attr(text):
    """HTML-escape for double-quoted attribute values: adds " on top of `_escape`.

    Titles/descriptions land in `content="..."` meta/OG tags, so an unescaped
    double quote in a description would truncate the attribute. Apostrophes are
    left literal (valid inside double-quoted attributes)."""
    return _escape(text).replace('"', "&quot;")


def _unescape(text):
    """Reverse `_escape` so a title read out of index.html matches its plain form."""
    return (
        text.replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", '"')
        .replace("&amp;", "&")
    )


# The "Writing & talks" section is a flat, regular structure (no nested <ul>/<li>),
# so these narrow regexes are enough to read and rewrite it without a real parser.
GROUP_LABEL_RE = re.compile(r'<span class="group-label">(.*?)</span>', re.DOTALL)
WRITING_LIST_RE = re.compile(r'<ul class="writing-list">(.*?)</ul>', re.DOTALL)
ITEM_BLOCK_RE = re.compile(
    r'(?P<indent>[ \t]*)<li class="writing-item"(?P<attrs>[^>]*)>(?P<inner>.*?)</li>',
    re.DOTALL,
)
ANCHOR_RE = re.compile(
    r'<a class="writing-title"[^>]*href="(?P<href>[^"]*)"[^>]*>(?P<text>.*?)</a>',
    re.DOTALL,
)
LOCAL_HREF_RE = re.compile(r'^posts/(?P<slug>[\w-]+)\.html$')
DATA_DATE_RE = re.compile(r'data-date="(\d{4}-\d{2}-\d{2})"')
SUBTITLE_YEAR_RE = re.compile(r'<p class="writing-meta">\s*(\d{4})')


def _item_title(inner):
    """Canonical (plain-text) title of an item, used as its stable identity."""
    am = ANCHOR_RE.search(inner)
    if not am:
        return None
    return _unescape(re.sub(r"\s+", " ", am.group("text")).strip())


def _item_date(item, posts_meta):
    """Resolve an item's date for the 'Recent' sort (newest first).

    Local posts use their frontmatter date. External items use their `data-date`
    attribute (sort-only; the day can be approximate), falling back to the year
    shown in the subtitle if that attribute is missing.
    """
    slug = item["slug"]
    if slug and slug in posts_meta:
        return posts_meta[slug]["date"]
    if item["data_date"]:
        return datetime.strptime(item["data_date"], "%Y-%m-%d").date()
    ym = SUBTITLE_YEAR_RE.search(item["inner"])
    if ym:
        print(
            f"  ! '{item['title']}' has no data-date; sorting it as {ym.group(1)}-01-01"
        )
        return datetime.strptime(f"{ym.group(1)}-01-01", "%Y-%m-%d").date()
    print(f"  ! '{item['title']}' has no date; it will sort last in 'Recent'")
    return datetime.min.date()


def _parse_writing_groups(html):
    """Read the "Writing & talks" section into [(label, [item dicts]), ...]."""
    labels = [_unescape(m.group(1).strip()) for m in GROUP_LABEL_RE.finditer(html)]
    lists = [m.group(1) for m in WRITING_LIST_RE.finditer(html)]
    groups = []
    for label, list_html in zip(labels, lists):
        items = []
        for m in ITEM_BLOCK_RE.finditer(list_html):
            inner = m.group("inner")
            am = ANCHOR_RE.search(inner)
            if not am:
                continue
            href = am.group("href")
            local = LOCAL_HREF_RE.match(href)
            dd = DATA_DATE_RE.search(m.group("attrs"))
            items.append(
                {
                    "title": _item_title(inner),
                    "slug": local.group("slug") if local else None,
                    "data_date": dd.group(1) if dd else None,
                    "inner": inner,
                }
            )
        groups.append((label, items))
    return groups


def _sync_order_file(groups):
    """Read/refresh curated-order.txt and return {label: [titles in curated order]}.

    The user's manual ordering is preserved; new items are appended to their
    group and items no longer in index.html are dropped.
    """
    existing = {}
    current = None
    if ORDER_PATH.exists():
        for line in ORDER_PATH.read_text().splitlines():
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            if s.startswith("[") and s.endswith("]"):
                current = s[1:-1].strip()
                existing.setdefault(current, [])
            elif current is not None:
                existing[current].append(s)

    order = {}
    for label, items in groups:
        titles = [it["title"] for it in items]
        kept = [t for t in existing.get(label, []) if t in titles]
        appended = [t for t in titles if t not in kept]
        order[label] = kept + appended

    lines = [ORDER_HEADER.rstrip("\n")]
    for label, _ in groups:
        lines.append("")
        lines.append(f"[{label}]")
        lines.extend(order[label])
    text = "\n".join(lines) + "\n"

    ORDER_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not ORDER_PATH.exists() or ORDER_PATH.read_text() != text:
        ORDER_PATH.write_text(text)
        print(f"  {ORDER_PATH} synced")
    return order


def update_index(posts_meta):
    """Regenerate the "Writing & talks" section's per-item sort metadata.

    For every item this writes two CSS custom properties on the <li> —
    `--o-cur` (curated rank, from curated-order.txt) and `--o-rec` (recency
    rank, from dates) — plus a `data-date`. Local posts additionally get their
    `writing-meta` subtitle refreshed from frontmatter. Ordering/grouping of the
    DOM and all external-link markup are otherwise left untouched.
    """
    if not INDEX_PATH.exists():
        print("No index.html found; skipping writing-section sync.")
        return

    html = INDEX_PATH.read_text()
    groups = _parse_writing_groups(html)
    if not groups:
        print("No .writing-group markup found; skipping writing-section sync.")
        return

    curated = _sync_order_file(groups)

    # Build a per-title lookup of the computed ranks + resolved date.
    meta_by_title = {}
    for label, items in groups:
        for it in items:
            it["date"] = _item_date(it, posts_meta)
        recent = sorted(range(len(items)), key=lambda i: items[i]["date"], reverse=True)
        rec_rank = {idx: rank for rank, idx in enumerate(recent)}
        cur_order = curated.get(label, [t["title"] for t in items])
        for idx, it in enumerate(items):
            try:
                cur_rank = cur_order.index(it["title"])
            except ValueError:
                cur_rank = len(cur_order) + idx
            meta_by_title[it["title"]] = {
                "date": it["date"].strftime("%Y-%m-%d"),
                "cur": cur_rank,
                "rec": rec_rank[idx],
            }

    filled = []

    def repl(m):
        indent = m.group("indent")
        inner = m.group("inner")
        am = ANCHOR_RE.search(inner)
        if not am:
            return m.group(0)
        title = _item_title(inner)
        info = meta_by_title.get(title)
        if not info:
            return m.group(0)

        href = am.group("href")
        local = LOCAL_HREF_RE.match(href)
        slug = local.group("slug") if local else None
        if slug and slug in posts_meta:
            # Regenerate the subtitle from frontmatter; keep the anchor verbatim.
            year = posts_meta[slug]["year"]
            desc = _escape(posts_meta[slug]["description"])
            child = indent + "    "
            new_inner = (
                f'\n{child}{am.group(0)}'
                f'\n{child}<p class="writing-meta">{year} · {desc}</p>'
                f"\n{indent}"
            )
            filled.append(slug)
        else:
            new_inner = inner  # external item: leave the hand-written markup alone

        opening = (
            f'<li class="writing-item" data-date="{info["date"]}" '
            f'style="--o-cur: {info["cur"]}; --o-rec: {info["rec"]};">'
        )
        return f"{indent}{opening}{new_inner}</li>"

    new_html = ITEM_BLOCK_RE.sub(repl, html)
    if new_html != html:
        INDEX_PATH.write_text(new_html)
    print(f"  index.html <- sort metadata for {len(meta_by_title)} item(s), "
          f"subtitles for {len(filled)} post(s)")


def main():
    if not CONTENT_DIR.exists():
        print(f"No content directory at {CONTENT_DIR}")
        sys.exit(1)

    posts = sorted(CONTENT_DIR.glob("*.md"))
    if not posts:
        print("No markdown files found.")
        return

    print(f"Building {len(posts)} post(s)...")
    posts_meta = {}
    for p in posts:
        slug, year, description, date = build_post(p)
        posts_meta[slug] = {"year": year, "description": description, "date": date}
    update_index(posts_meta)
    print("Done.")


if __name__ == "__main__":
    main()
