#!/usr/bin/env python3
"""Build blog posts from Markdown to HTML."""

import html
import re
import sys
import textwrap
from datetime import date, datetime
from pathlib import Path

try:
    import markdown
    import yaml
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("Missing dependencies. Install with: pip install markdown pyyaml Pillow")
    sys.exit(1)

CONTENT_DIR = Path("content/posts")
OUTPUT_DIR = Path("posts")
FONT_PATH = Path("files/fonts/EBGaramond.ttf")
OG_DIR = OUTPUT_DIR / "og"

WRITING_FILE = Path("content/writing.yaml")
WRITING_PAGE = Path("writing.html")
INDEX_FILE = Path("index.html")
HOMEPAGE_FEATURED_LIMIT = 5

# Order + display labels for the type filter chips on /writing.html.
TYPE_LABELS = {
    "essay": "Essay",
    "external": "External",
    "talk": "Talk",
    "podcast": "Podcast",
}
CHIP_LABELS = {
    "essay": "Essays",
    "external": "External",
    "talk": "Talks",
    "podcast": "Podcasts",
}

TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - David Rein</title>
    <link rel="stylesheet" href="../styles.css">
    <link rel="apple-touch-icon" sizes="180x180" href="../files/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../files/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../files/favicon/favicon-16x16.png">
    <link rel="manifest" href="../files/favicon/site.webmanifest">
    <meta name="description" content="{description}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description}">
    <meta property="og:image" content="https://idavidrein.com/posts/og/{slug}.png">
    <meta property="og:type" content="article">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{title}">
    <meta name="twitter:description" content="{description}">
    <meta name="twitter:image" content="https://idavidrein.com/posts/og/{slug}.png">
</head>
<body>
    <div class="page">
        <nav class="post-nav">
            <a href="/">&larr; Home</a>
        </nav>

        <article class="post">
            <header class="post-header">
                <h1>{title}</h1>
                <time class="post-date" datetime="{date_iso}">{date_display}</time>
            </header>

            <div class="post-body">
                {body}
            </div>
        </article>
    </div>
    <script src="../footnotes.js"></script>
</body>
</html>
"""

WRITING_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Writing &amp; talks - David Rein</title>
    <link rel="stylesheet" href="styles.css">
    <link rel="apple-touch-icon" sizes="180x180" href="files/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="files/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="files/favicon/favicon-16x16.png">
    <link rel="manifest" href="files/favicon/site.webmanifest">
    <meta name="description" content="Essays, external writing, talks, and podcast appearances by David Rein.">
</head>
<body>
    <div class="page">
        <nav class="post-nav">
            <a href="/">&larr; Home</a>
        </nav>

        <header class="post-header">
            <h1>Writing &amp; talks</h1>
            <p class="post-date">Essays, external writing, talks, and podcast appearances.</p>
        </header>

        <div class="writing-controls">
            <input type="search" id="writing-search" class="writing-search" placeholder="Search by title, topic, or tag…" aria-label="Search writing and talks" autocomplete="off">
            <div class="filter-chips" id="filter-chips" role="group" aria-label="Filter by type">
{chips}
            </div>
        </div>

        <p class="writing-count" id="writing-count" aria-live="polite"></p>

        <ul class="writing-list" id="writing-list">
{items}
        </ul>

        <p class="writing-empty" id="writing-empty" hidden>No matching items. <button type="button" class="link-button" id="clear-filters">Clear filters</button></p>
    </div>
    <script src="writing.js"></script>
</body>
</html>
"""


def parse_frontmatter(text):
    """Parse YAML frontmatter from markdown text."""
    if not text.startswith("---"):
        raise ValueError("No frontmatter found")
    end = text.index("---", 3)
    meta = yaml.safe_load(text[3:end])
    body = text[end + 3 :].strip()
    return meta, body


def process_footnotes(html):
    """Convert bottom-of-page footnotes into inline popup spans."""
    # Find the footnote section generated by python-markdown
    fn_match = re.search(
        r'<div class="footnote">\s*<hr\s*/?>\s*<ol>(.*?)</ol>\s*</div>',
        html,
        re.DOTALL,
    )
    if not fn_match:
        return html

    # Extract each footnote's content
    footnotes = {}
    for li in re.finditer(
        r'<li id="fn:(.+?)">\s*(.*?)\s*</li>', fn_match.group(1), re.DOTALL
    ):
        fn_id = li.group(1)
        content = li.group(2)
        # Remove the backref link and its preceding non-breaking space
        content = re.sub(
            r"\s*&#160;\s*<a [^>]*class=\"footnote-backref\"[^>]*>.*?</a>",
            "",
            content,
        )
        content = content.strip()
        # Unwrap single-paragraph footnotes
        if content.startswith("<p>") and content.endswith("</p>") and content.count("<p>") == 1:
            content = content[3:-4].strip()
        footnotes[fn_id] = content

    # Remove the footnote section
    html = html[: fn_match.start()] + html[fn_match.end() :]

    # Replace each reference with a popup span
    def replace_ref(m):
        fn_id = m.group(1)
        num = m.group(2)
        content = footnotes.get(fn_id, "")
        return (
            f'<span class="footnote-ref" tabindex="0" role="button" '
            f'aria-label="Footnote {num}">'
            f"<sup>{num}</sup>"
            f'<span class="footnote-popup" role="tooltip">{content}</span>'
            f"</span>"
        )

    # fnref\d* handles repeated references (fnref2:, fnref3:, etc.)
    html = re.sub(
        r'<sup id="fnref\d*:(.+?)"><a class="footnote-ref" href="#fn:.+?">(\d+)</a></sup>',
        replace_ref,
        html,
    )

    return html


def _wrap_text(title, font, max_w):
    """Word-wrap title by measuring with the font."""
    words = title.split()
    lines = []
    current = ""
    for word in words:
        test = f"{current} {word}".strip()
        if font.getbbox(test)[2] > max_w and current:
            lines.append(current)
            current = word
        else:
            current = test
    if current:
        lines.append(current)
    return lines


def generate_og_image(title, slug):
    """Generate a 1200x630 OG image with the post title."""
    W, H = 1200, 630
    BG = (247, 245, 242)  # --bg
    INK = (31, 41, 51)  # --ink
    pad_x = 80

    MUTED = (107, 114, 128)  # --muted
    font_site = ImageFont.truetype(str(FONT_PATH), size=56)
    site_h = 100  # space reserved for site name at bottom

    # Pick the largest font size that fits the title above the site name
    max_text_w = W - 2 * pad_x
    for size in range(140, 30, -2):
        font = ImageFont.truetype(str(FONT_PATH), size=size)
        line_h = int(size * 1.35)
        lines = _wrap_text(title, font, max_text_w)
        text_h = line_h * len(lines)
        if text_h <= H - 80 - site_h:
            break

    img = Image.new("RGB", (W, H), BG)
    draw = ImageDraw.Draw(img)

    # Center title vertically in the space above the site name
    title_area_h = H - site_h
    y = (title_area_h - text_h) // 2
    for line in lines:
        draw.text((pad_x, y), line, fill=INK, font=font)
        y += line_h

    # Site name at bottom
    draw.text((pad_x, H - site_h), "idavidrein.com", fill=MUTED, font=font_site)

    out_path = OG_DIR / f"{slug}.png"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_path, "PNG")


def open_links_in_new_tab(html):
    """Add target="_blank" rel="noreferrer" to external links."""
    return re.sub(r"<a ", '<a target="_blank" rel="noreferrer" ', html)


def build_post(md_path):
    """Convert a single markdown file to HTML."""
    text = md_path.read_text()
    meta, body_md = parse_frontmatter(text)

    md = markdown.Markdown(extensions=["footnotes", "smarty"])
    body_html = md.convert(body_md)
    body_html = process_footnotes(body_html)
    body_html = open_links_in_new_tab(body_html)

    date = meta["date"]
    if isinstance(date, str):
        date = datetime.strptime(date, "%Y-%m-%d")
    date_iso = date.strftime("%Y-%m-%d")
    date_display = f"{date.strftime('%B')} {date.day}, {date.year}"

    slug = meta.get("slug", md_path.stem)
    out_path = OUTPUT_DIR / f"{slug}.html"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        TEMPLATE.format(
            title=meta["title"],
            description=meta.get("description", ""),
            date_iso=date_iso,
            date_display=date_display,
            body=body_html,
            slug=slug,
        )
    )
    generate_og_image(meta["title"], slug)
    print(f"  {md_path} -> {out_path}")


def _entry_date(raw):
    """Return (display_year, sort_key) for a writing.yaml date.

    Accepts a full date (YYYY-MM-DD) or a bare year. Only the year is
    ever displayed; the full date, when present, refines sort order
    within a year.
    """
    if isinstance(raw, datetime):
        raw = raw.date()
    if isinstance(raw, date):
        return raw.year, (raw.year, raw.month, raw.day)
    if isinstance(raw, int):
        return raw, (raw, 0, 0)
    if isinstance(raw, str):
        parts = raw.strip().split("-")
        year = int(parts[0])
        month = int(parts[1]) if len(parts) > 1 else 0
        day = int(parts[2]) if len(parts) > 2 else 0
        return year, (year, month, day)
    raise ValueError(f"Unrecognized date: {raw!r}")


def load_writing():
    """Load and validate writing.yaml, newest first."""
    if not WRITING_FILE.exists():
        return []
    raw = yaml.safe_load(WRITING_FILE.read_text()) or []
    entries = []
    for item in raw:
        for field in ("title", "url", "date", "type", "description"):
            if field not in item:
                raise ValueError(f"writing.yaml entry missing '{field}': {item}")
        if item["type"] not in TYPE_LABELS:
            raise ValueError(
                f"writing.yaml unknown type {item['type']!r} "
                f"(expected one of {', '.join(TYPE_LABELS)})"
            )
        year, sort_key = _entry_date(item["date"])
        entries.append(
            {
                "title": str(item["title"]).strip(),
                "url": str(item["url"]).strip(),
                "type": item["type"],
                "tags": [str(t).strip() for t in item.get("tags", [])],
                "description": str(item["description"]).strip(),
                "featured": bool(item.get("featured", False)),
                "year": year,
                "sort_key": sort_key,
            }
        )
    entries.sort(key=lambda e: e["sort_key"], reverse=True)
    return entries


def _link_attrs(url):
    """External links open in a new tab; internal ones stay in-tab."""
    if url.startswith("/") or url.startswith("#"):
        return ""
    return ' target="_blank" rel="noreferrer"'


def _esc_text(value):
    """Escape for HTML text content (keep quotes/apostrophes literal)."""
    return html.escape(str(value), quote=False)


def _esc_attr(value):
    """Escape for an HTML attribute value."""
    return html.escape(str(value), quote=True)


def render_homepage_li(entry, indent):
    """Compact list item for the curated homepage list."""
    pad = " " * indent
    href = _esc_attr(entry["url"])
    attrs = _link_attrs(entry["url"])
    return (
        f'{pad}<li>\n'
        f'{pad}    <div class="writing-row">\n'
        f'{pad}        <span class="writing-year">{entry["year"]}</span>\n'
        f'{pad}        <a href="{href}"{attrs}>\n'
        f'{pad}            {_esc_text(entry["title"])}\n'
        f'{pad}        </a>\n'
        f'{pad}    </div>\n'
        f'{pad}    <p>{_esc_text(entry["description"])}</p>\n'
        f'{pad}</li>'
    )


def render_page_li(entry):
    """Full list item for /writing.html, with filter metadata."""
    href = _esc_attr(entry["url"])
    attrs = _link_attrs(entry["url"])
    type_label = TYPE_LABELS[entry["type"]]
    haystack = " ".join(
        [
            entry["title"],
            entry["description"],
            " ".join(entry["tags"]),
            type_label,
            str(entry["year"]),
        ]
    ).lower()
    tag_buttons = "".join(
        f'<button type="button" class="tag" data-tag="{_esc_attr(t)}">'
        f"{_esc_text(t)}</button>"
        for t in entry["tags"]
    )
    return (
        f'            <li class="writing-item" data-type="{entry["type"]}" '
        f'data-tags="{_esc_attr(" ".join(entry["tags"]))}" '
        f'data-text="{_esc_attr(haystack)}">\n'
        f'                <div class="writing-row">\n'
        f'                    <span class="writing-year">{entry["year"]}</span>\n'
        f'                    <a href="{href}"{attrs}>{_esc_text(entry["title"])}</a>\n'
        f'                </div>\n'
        f'                <p>{_esc_text(entry["description"])}</p>\n'
        f'                <div class="entry-meta">\n'
        f'                    <span class="entry-type entry-type-{entry["type"]}">'
        f"{type_label}</span>"
        f"{tag_buttons}\n"
        f'                </div>\n'
        f"            </li>"
    )


def build_writing_page(entries):
    """Write the searchable /writing.html archive."""
    present = [t for t in TYPE_LABELS if any(e["type"] == t for e in entries)]
    chips = ['                <button type="button" class="chip" '
             'data-type="all" aria-pressed="true">All</button>']
    for t in present:
        chips.append(
            f'                <button type="button" class="chip" '
            f'data-type="{t}" aria-pressed="false">{CHIP_LABELS[t]}</button>'
        )
    items = "\n".join(render_page_li(e) for e in entries)
    WRITING_PAGE.write_text(
        WRITING_TEMPLATE.format(chips="\n".join(chips), items=items)
    )
    print(f"  {WRITING_FILE} -> {WRITING_PAGE} ({len(entries)} entries)")


def inject_homepage_list(entries):
    """Replace the marked block in index.html with the curated list."""
    if not INDEX_FILE.exists():
        return
    text = INDEX_FILE.read_text()
    marker = re.compile(
        r"(<!-- WRITING:START -->).*?(<!-- WRITING:END -->)", re.DOTALL
    )
    if not marker.search(text):
        print(
            "  WARNING: WRITING:START/END markers not found in index.html; "
            "skipping homepage injection."
        )
        return
    featured = [e for e in entries if e["featured"]][:HOMEPAGE_FEATURED_LIMIT]
    if not featured:
        featured = entries[:HOMEPAGE_FEATURED_LIMIT]
    block = "\n".join(render_homepage_li(e, 20) for e in featured)

    def _replace(m):
        return f'{m.group(1)}\n{block}\n' + " " * 20 + m.group(2)

    INDEX_FILE.write_text(marker.sub(_replace, text))
    print(f"  {WRITING_FILE} -> {INDEX_FILE} ({len(featured)} featured)")


def main():
    if not CONTENT_DIR.exists():
        print(f"No content directory at {CONTENT_DIR}")
        sys.exit(1)

    posts = sorted(CONTENT_DIR.glob("*.md"))
    if not posts:
        print("No markdown files found.")
        return

    print(f"Building {len(posts)} post(s)...")
    for p in posts:
        build_post(p)

    entries = load_writing()
    if entries:
        print(f"Building writing index ({len(entries)} entries)...")
        build_writing_page(entries)
        inject_homepage_list(entries)
    print("Done.")


if __name__ == "__main__":
    main()
